# SLT: 'slt.deployment' from templates/_deployment.tpl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lars-server
  labels:
    app: lars-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lars-server
  template:
    metadata:
      annotations:
        productName: IBM WebSphere Application Server Liberty
        productID: IBMWebSphereLiberty_5724J08_18002_151_00000
        productVersion: 19.0.0.2
      labels:
        app: lars-server
    spec:      
      # SLT: 'slt.security.context.pod' from templates/_security-context.tpl
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        fsGroup: 
      volumes:
      - name: liberty-overrides
        configMap:
          name: lars-config
          items:
          - key: include-configmap.xml
            path: include-configmap.xml
      - name: liberty-config
        configMap:
          name: lars-config
      serviceAccountName: lars-server
      affinity:      # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          # If you specify multiple nodeSelectorTerms associated with nodeAffinity types,
          # then the pod can be scheduled onto a node if one of the nodeSelectorTerms is satisfied.
          #
          # If you specify multiple matchExpressions associated with nodeSelectorTerms,
          # then the pod can be scheduled onto a node only if all matchExpressions can be satisfied.
          #
          # valid operators: In, NotIn, Exists, DoesNotExist, Gt, Lt
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
      
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - lars-server
              topologyKey: kubernetes.io/hostname
      containers:
      - name: ibm-websphere-liberty        
        # SLT: 'slt.security.context.container' from templates/_security-context.tpl
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 20
          periodSeconds: 5
        image: "docker-registry.default.svc:5000/lars-server/lars-server:latest"
        imagePullPolicy: Always
        env:
        - name: WLP_LOGGING_CONSOLE_FORMAT
          value: json
        - name: WLP_LOGGING_CONSOLE_LOGLEVEL
          value: info
        - name: WLP_LOGGING_CONSOLE_SOURCE
          value: message,trace,accessLog,ffdc
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IIOP_ENDPOINT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name : KEYSTORE_REQUIRED
          value: "false"
        volumeMounts:
        - name: liberty-overrides
          mountPath: /config/configDropins/overrides/include-configmap.xml
          subPath: include-configmap.xml
          readOnly: true
        - name: liberty-config
          mountPath: /etc/wlp/configmap
          readOnly: true
        resources:
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      dnsPolicy: "ClusterFirst"
