# SLT: 'slt.service' from templates/_service.tpl
apiVersion: v1
kind: Service
metadata:
  name: lars-server
  annotations:
  labels:
    app: lars-ibm-websphere-liber
spec:  
  type: ClusterIP
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: "http"
  selector:
    app: lars-server
